### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by csezoli21** [mavrikkk/hassio-addons#1]
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:119
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 20:40:59 (1 occurrences)
Last logged: 20:40:59

Failed to to call /addons/3816fe87_upmpdcli/install - The command '/bin/ash -o pipefail -c apk add --no-cache python3 && apk add --no-cache openssl && apk add --no-cache alsa-plugins-pulse --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community/ && apk add --no-cache libmpdclient --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community/ && apk add --no-cache libmicrohttpd --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community/ && apk add --no-cache jsoncpp --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community/ && apk add --no-cache libnpupnp --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community/ && apk add --no-cache upmpdcli --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing/ && apk add --no-cache mpd --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community/' returned a non-zero code: 4

**Comment by mavrikkk** [comment]
yes,  thanks for your comment. i'll try to find time to update this addon. i think, ha changed his base image or some packages are no more available.

**Comment by mavrikkk** [comment]
fixed
